- name: Demo on Vars
  hosts: localhost
  # If we declare variable here (play level) then all the tasks can access this variable
  vars:
    URL: role.google.com
  tasks:
    - name: print play level variable
      ansible.builtin.debug:
         msg: URL = {{ URL }}

    - name: print variable declared in task
      vars:
        URL: task.google.come
      ansible.builtin.debug:
        msg: URL = {{ URL }}

  roles:
    - demo
