- name: Demo on condition
  hosts: localhost
  tasks:
    - name: say hi to john
      ansible.builtin.debug:
        msg: hello , john
      when: user == "john"

    - name: say Hi to Ram
      ansible.builtin.debug:
        msg: hello, ram
      when: user == "Ram"