- name: Loops
  hosts: localhost
  tasks:
    - name: Loop Demo
      ansible.builtin.debug:
        msg: Hello , {{ item }}
      loop:
        - Ram
        - john
        - steve

    - name: Loop Demo on maps
      ansible.builtin.debug:
        msg: Hello , {{ item }}
      loop:
        - { name: "Ram", age: 20 }
        - { name: "john", age: 30 }
        - { name: "steve", age: 40 }