- name: Handlers demo
  hosts: localhost
  tasks:
   - name: copy sample
     ansible.builtin.template:
        src: sample.txt
        dest: /tmp/sample.txt

  handlers:
   - name: Say Hello again
     ansible.builtin.debug:
       msg: Hello {{ name }} again!!