- name: Rescue demo
  hosts: localhost
  tasks:
    - name: block
      block:
        - name: Run shell command
          ansible.builtin.shell: exit 1

        - name: Say Hai
          ansible.builtin.debug:
            msg: Hai